# Secure Cloud Build Configuration for Noctua Rhyme App
# This replaces the insecure .git/cloudbuild.yaml

steps:
  # Create .env file with secrets
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating .env file..."
        echo "VITE_FIREBASE_API_KEY=$$FIREBASE_API_KEY" > noctua-forest/.env.local
        echo "VITE_FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN" >> noctua-forest/.env.local
        echo "VITE_FIREBASE_PROJECT_ID=$PROJECT_ID" >> noctua-forest/.env.local
        echo "VITE_FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET" >> noctua-forest/.env.local
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID" >> noctua-forest/.env.local
        echo "VITE_FIREBASE_APP_ID=$$FIREBASE_APP_ID" >> noctua-forest/.env.local
    secretEnv: ['FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID']

  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'noctua-forest'

  # Build the app
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'noctua-forest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'noctua-forest-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/noctua-forest:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

# Secrets configuration - must be set up in Secret Manager first
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest
      env: 'FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/firebase-auth-domain/versions/latest
      env: 'FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/firebase-storage-bucket/versions/latest
      env: 'FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/firebase-messaging-sender-id/versions/latest
      env: 'FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/firebase-app-id/versions/latest
      env: 'FIREBASE_APP_ID'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s' 