services:
  backend:
    build:
      context: ./node-backend
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - ./node-backend/.env
    volumes:
      - ./node-backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./node-backend/.env
