// Shared sample dataset and cover resolver for listing and detail views
(function(){
  const SAMPLE_BOOKS = [
    { id: 1, title: "Klara and the Sun", author: "Kazuo Ishiguro", language: "en", region: "europe", blurb: "An artificial friend observes the world with profound questions about what it means to love. From the Nobel Prize-winning author of Never Let Me Go and The Remains of the Day comes a luminous meditation on love, loss, and what it means to be human. Klara, an Artificial Friend with outstanding observational qualities, watches from the store window hoping a child will choose her. When fourteen-year-old Josie arrives, Klara is chosen to be her companion. But beneath the surface, nothing is quite as it seems in this haunting story of artificial intelligence and the human heart.", tags: ["science fiction", "nobel prize", "philosophical"], rating: 4.1, year: 2021, isbn: "9780593318188", amazonUrl: "https://amazon.com/dp/0593318188" },
    { id: 2, title: "The Midnight Library", author: "Matt Haig", language: "en", region: "europe", blurb: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be different if you had made other choices. Would you have done anything different, if you had the chance to undo your regrets? A dazzling novel about all the choices that go into a life well lived, from the internationally bestselling author of Reasons to Stay Alive and How To Stop Time. This is a story about possibility, about living without regret.", tags: ["philosophical fiction", "contemporary", "british literature"], rating: 4.2, year: 2020, isbn: "9780525559474", amazonUrl: "https://amazon.com/dp/0525559477" },
    { id: 3, title: "Circe", author: "Madeline Miller", language: "en", region: "north-america", blurb: "The story of the Greek goddess who transforms from an awkward nymph into a formidable witch. In this stunning feminist retelling of Greek mythology, Circe discovers her powers of witchcraft when she turns to the world of mortals for companionship. From the author of The Song of Achilles comes this breathtaking novel of gods and heroes, magic and monsters, survival and transformation. A bold and subversive retelling of the goddess's story, this epic tale of family rivalry, palace intrigue, love and loss turns the page on the tales we think we know.", tags: ["mythology", "fantasy", "feminist retelling"], rating: 4.3, year: 2018, isbn: "9780316556347", amazonUrl: "https://amazon.com/dp/0316556343" },
    { id: 4, title: "Project Hail Mary", author: "Andy Weir", language: "en", region: "north-america", blurb: "A lone astronaut must save the earth from disaster with the help of an unexpected ally. Ryland Grace wakes up on a spaceship with no memory of why he's there. His crewmates are dead. His memories are slowly returning. And he realizes that an impossible task now confronts him. Ever since he was a kid, Ryland dreamed of being a teacher. Now he must use all his knowledge and skills to save humanity itself. From the author of The Martian comes an irresistible new near-future thriller about one man's quest to save humanity, featuring his trademark mix of rigorous science, humor, and heart.", tags: ["science fiction", "space adventure", "humor"], rating: 4.5, year: 2021, isbn: "9780593135204", amazonUrl: "https://amazon.com/dp/0593135202" },
    { id: 5, title: "Pachinko", author: "Min Jin Lee", language: "en", region: "asia", blurb: "A sweeping saga of a Korean family through four generations, navigating love, war, and survival. In the early 1900s, teenage Sunja becomes pregnant by a married yakuza and accepts an offer of marriage from a gentle minister passing through town. Following her family through the decades that span the Japanese occupation, World War II, the Korean War, and beyond, this epic novel chronicles the hopes and dreams of four generations of one family. It's a story of love, sacrifice, ambition, and loyalty that asks what we owe our families and what we owe ourselves.", tags: ["historical fiction", "family saga", "korean-american"], rating: 4.5, year: 2017, isbn: "9781455563937", amazonUrl: "https://amazon.com/dp/1455563935" },
    { id: 6, title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", language: "en", region: "north-america", blurb: "Reclusive Hollywood icon Evelyn Hugo finally tells her life story to an unknown journalist. When reclusive Hollywood icon Evelyn Hugo finally decides to tell her life story, she selects unknown magazine reporter Monique Grant for the job. Nobody understands why. Evelyn's story spans decades of ruthless ambition, unexpected friendship, and a great forbidden love. But as the two women grow closer, it becomes clear that Evelyn's life intersects with Monique's own in tragic and irreversible ways. This is a mesmerizing journey through the splendor of old Hollywood into the harsh realities of the present day.", tags: ["contemporary fiction", "lgbtq", "hollywood"], rating: 4.6, year: 2017, isbn: "9781501161933", amazonUrl: "https://amazon.com/dp/1501161938" },
    { id: 7, title: "Educated", author: "Tara Westover", language: "en", region: "north-america", blurb: "A memoir about a woman who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University. Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent. When another brother got himself into college, Tara decided to try a new kind of life. Her quest for knowledge transformed her, taking her over oceans and across continents to Harvard and Cambridge University.", tags: ["memoir", "education", "family"], rating: 4.4, year: 2018, isbn: "9780399590504", amazonUrl: "https://amazon.com/dp/0399590501" },
    { id: 8, title: "The Song of Achilles", author: "Madeline Miller", language: "en", region: "north-america", blurb: "A tale of gods, kings, immortal fame and the human heart, this is a dazzling literary feat that brilliantly reimagines Homer's enduring masterwork, The Iliad. An action-packed adventure, an epic love story, a marvelously conceived and executed page-turner, Miller's monumental debut novel has already earned her a place among the greatest contemporary writers of historical fiction. At once a scholar's homage to The Iliad and startlingly original work of art by an incredibly talented new novelist, this is destined to become a classic. Patroclus, an awkward young prince, follows Achilles into war, little knowing that the years that follow will test everything they hold dear.", tags: ["mythology", "historical fiction", "lgbtq"], rating: 4.4, year: 2011, isbn: "9780062060624", amazonUrl: "https://amazon.com/dp/0062060627" }
  ];

  function coverFor(book){
    const titleMap = {
      'klara and the sun': 'books_cover_sample_templates/klara and the sun.jpg',
      'the midnight library': 'books_cover_sample_templates/midnight_library.jpg',
      'circe': 'books_cover_sample_templates/circe.jpg',
      'project hail mary': 'books_cover_sample_templates/project_hail_mary.jpg',
      'pachinko': 'books_cover_sample_templates/pachinko.jpg',
      'educated': 'books_cover_sample_templates/educated.jpg'
    };
    const samples = Object.values(titleMap);
    const norm = (book.title || '').toLowerCase().replace(/\s+/g,' ').trim();
    const mapped = titleMap[norm];
    const sampleUrl = samples[(book.id || 0) % samples.length];
    return book.coverUrl || mapped || sampleUrl;
  }

  window.SAMPLE_BOOKS = SAMPLE_BOOKS;
  window.coverFor = coverFor;
})();


