@echo off
echo ========================================
echo Noctua Environment Setup Script
echo ========================================
echo.

REM Check if parent .env exists
if exist "..\.env" (
    echo Found parent .env file!
    echo Contents:
    echo ----------------------------------------
    type ..\.env
    echo ----------------------------------------
    echo.
    echo This script will help you split these variables into:
    echo - node-backend\.env (for backend)
    echo - my-rhyme-app\.env.local (for frontend)
    echo.
    pause
) else (
    echo No parent .env file found.
    echo You'll need to create the environment files manually.
    echo.
)

REM Create node-backend\.env
echo Creating node-backend\.env...
if not exist "node-backend" mkdir node-backend
(
echo # Backend Environment Variables
echo # Generated by setup-env.bat
echo.
echo # Anthropic API Key for AI-powered analysis
echo ANTHROPIC_API_KEY=your_anthropic_api_key_here
echo.
echo # Frontend URL for CORS
echo FRONTEND_URL=http://localhost:5173
echo.
echo # Server Port
echo PORT=3001
echo.
echo # Optional: Firebase Admin SDK path
echo # FIREBASE_ADMIN_CREDENTIALS=../secrets/firebase-adminsdk.json
) > node-backend\.env.template

echo Created node-backend\.env.template
echo.

REM Create my-rhyme-app\.env.local
echo Creating my-rhyme-app\.env.local...
if not exist "my-rhyme-app" mkdir my-rhyme-app
(
echo # Frontend Environment Variables
echo # Generated by setup-env.bat
echo.
echo # Firebase Configuration
echo # Get these from Firebase Console > Project Settings
echo VITE_FIREBASE_API_KEY=your_firebase_api_key
echo VITE_FIREBASE_AUTH_DOMAIN=your-app.firebaseapp.com
echo VITE_FIREBASE_PROJECT_ID=your-project-id
echo VITE_FIREBASE_STORAGE_BUCKET=your-app.appspot.com
echo VITE_FIREBASE_MESSAGING_SENDER_ID=123456789012
echo VITE_FIREBASE_APP_ID=1:123456789012:web:abcdef123456
echo.
echo # API URL (optional - defaults to /api)
echo # VITE_API_URL=/api
) > my-rhyme-app\.env.local.template

echo Created my-rhyme-app\.env.local.template
echo.

echo ========================================
echo NEXT STEPS:
echo ========================================
echo 1. Edit node-backend\.env.template and add your actual API keys
echo 2. Rename it to node-backend\.env
echo 3. Edit my-rhyme-app\.env.local.template with your Firebase config
echo 4. Rename it to my-rhyme-app\.env.local
echo.
echo If you have a parent .env file, copy the relevant values:
echo - ANTHROPIC_API_KEY goes to node-backend\.env
echo - Firebase variables go to my-rhyme-app\.env.local (prefix with VITE_)
echo.
pause 