import React from 'react';

const TermsOfService: React.FC = () => (
  <div style={{ maxWidth: 700, margin: '0 auto', padding: 24 }}>
    <h2>Terms of Service</h2>
    <p>Last updated: June 2024</p>
    <h4>1. Acceptance of Terms</h4>
    <p>By creating an account or using this app, you agree to these Terms of Service. If you do not agree, do not use the app.</p>
    <h4>2. Copyright & Fair Use</h4>
    <p>
      You agree not to upload, analyze, or share copyrighted material unless you have the legal right to do so, or your use qualifies as "fair use" under applicable law. This tool is intended for educational, personal, and non-commercial analysis only. You are solely responsible for the content you submit.
    </p>
    <h4>3. User Conduct</h4>
    <ul>
      <li>Do not use the app for unlawful, harmful, or abusive purposes.</li>
      <li>Do not attempt to reverse engineer, disrupt, or overload the service.</li>
      <li>You are responsible for your account and all activity under it.</li>
    </ul>
    <h4>4. Disclaimer</h4>
    <p>
      This app is provided "as is" without warranties of any kind. We do not guarantee accuracy, availability, or fitness for a particular purpose.
    </p>
    <h4>5. Limitation of Liability</h4>
    <p>
      We are not liable for any damages or losses resulting from your use of the app.
    </p>
    <h4>6. Changes to Terms</h4>
    <p>
      We may update these terms at any time. Continued use of the app means you accept the new terms.
    </p>
    <h4>7. Contact</h4>
    <p>
      For questions, contact us at support@myrhymeapp.com.
    </p>
    <h4>8. AI-Generated Content</h4>
    <p>
      The analysis and results provided by this app are generated by artificial intelligence. While we strive for accuracy, you acknowledge that AI-generated content may contain errors or inaccuracies. You are solely responsible for how you use or interpret the results. You agree not to rely solely on the app for any critical or legal decisions.
    </p>
  </div>
);

export default TermsOfService; 